server:
  port: 8182
  servlet:
    session:
      cookie:
        name: analog

spring:
  application:
    name: analog
  main:
    banner-mode: log
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jackson:
    property-naming-strategy: SNAKE_CASE

analog:
  version: 1.0.2
